/*
 * generated by Xtext 2.38.0
 */
package org.simplequiz.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.simplequiz.dsl.ui.internal.DslActivator;

public class QuizDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("org.simplequiz.QuizDSL");
	}

}
