/*
 * generated by Xtext 2.38.0
 */
package org.simplequiz.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQuizDSLScopeProvider extends DelegatingScopeProvider {
}
