/*
 * generated by Xtext 2.38.0
 */
package org.simplequiz.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.simplequiz.services.QuizDSLGrammarAccess;

@SuppressWarnings("all")
public class QuizDSLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected QuizDSLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Quiz_BooleanLiteralParserRuleCall_5_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (QuizDSLGrammarAccess) access;
		match_Quiz_BooleanLiteralParserRuleCall_5_q = new TokenAlias(false, true, grammarAccess.getQuizAccess().getBooleanLiteralParserRuleCall_5());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getBooleanLiteralRule())
			return getbooleanLiteralToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * booleanLiteral:
	 *     'true' | 'false';
	 */
	protected String getbooleanLiteralToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "true";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Quiz_BooleanLiteralParserRuleCall_5_q.equals(syntax))
				emit_Quiz_BooleanLiteralParserRuleCall_5_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     booleanLiteral?
	 *
	 * This ambiguous syntax occurs at:
	 *     randomizeOrder?='randomizeOrder' '=' (ambiguity) '}' (rule end)
	 *     randomizeOrder?='randomizeOrder' '=' (ambiguity) questions+=Question
	 
	 * </pre>
	 */
	protected void emit_Quiz_BooleanLiteralParserRuleCall_5_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
