/**
 * generated by Xtext 2.38.0
 */
package org.simplequiz.quizDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Choice</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.simplequiz.quizDSL.Choice#getText <em>Text</em>}</li>
 *   <li>{@link org.simplequiz.quizDSL.Choice#getCorrectness <em>Correctness</em>}</li>
 * </ul>
 *
 * @see org.simplequiz.quizDSL.QuizDSLPackage#getChoice()
 * @model
 * @generated
 */
public interface Choice extends EObject
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see org.simplequiz.quizDSL.QuizDSLPackage#getChoice_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link org.simplequiz.quizDSL.Choice#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

  /**
   * Returns the value of the '<em><b>Correctness</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Correctness</em>' attribute.
   * @see #setCorrectness(String)
   * @see org.simplequiz.quizDSL.QuizDSLPackage#getChoice_Correctness()
   * @model
   * @generated
   */
  String getCorrectness();

  /**
   * Sets the value of the '{@link org.simplequiz.quizDSL.Choice#getCorrectness <em>Correctness</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Correctness</em>' attribute.
   * @see #getCorrectness()
   * @generated
   */
  void setCorrectness(String value);

} // Choice
