/**
 * generated by Xtext 2.38.0
 */
package org.simplequiz.quizDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.simplequiz.quizDSL.Model#getQuizzes <em>Quizzes</em>}</li>
 * </ul>
 *
 * @see org.simplequiz.quizDSL.QuizDSLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Quizzes</b></em>' containment reference list.
   * The list contents are of type {@link org.simplequiz.quizDSL.Quiz}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quizzes</em>' containment reference list.
   * @see org.simplequiz.quizDSL.QuizDSLPackage#getModel_Quizzes()
   * @model containment="true"
   * @generated
   */
  EList<Quiz> getQuizzes();

} // Model
