/**
 * generated by Xtext 2.38.0
 */
package org.simplequiz.quizDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Question</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.simplequiz.quizDSL.Question#getText <em>Text</em>}</li>
 *   <li>{@link org.simplequiz.quizDSL.Question#isCalculated <em>Calculated</em>}</li>
 *   <li>{@link org.simplequiz.quizDSL.Question#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.simplequiz.quizDSL.Question#getChoices <em>Choices</em>}</li>
 * </ul>
 *
 * @see org.simplequiz.quizDSL.QuizDSLPackage#getQuestion()
 * @model
 * @generated
 */
public interface Question extends EObject
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see org.simplequiz.quizDSL.QuizDSLPackage#getQuestion_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link org.simplequiz.quizDSL.Question#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

  /**
   * Returns the value of the '<em><b>Calculated</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Calculated</em>' attribute.
   * @see #setCalculated(boolean)
   * @see org.simplequiz.quizDSL.QuizDSLPackage#getQuestion_Calculated()
   * @model
   * @generated
   */
  boolean isCalculated();

  /**
   * Sets the value of the '{@link org.simplequiz.quizDSL.Question#isCalculated <em>Calculated</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Calculated</em>' attribute.
   * @see #isCalculated()
   * @generated
   */
  void setCalculated(boolean value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see org.simplequiz.quizDSL.QuizDSLPackage#getQuestion_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link org.simplequiz.quizDSL.Question#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Choices</b></em>' containment reference list.
   * The list contents are of type {@link org.simplequiz.quizDSL.Choice}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choices</em>' containment reference list.
   * @see org.simplequiz.quizDSL.QuizDSLPackage#getQuestion_Choices()
   * @model containment="true"
   * @generated
   */
  EList<Choice> getChoices();

} // Question
