/**
 * generated by Xtext 2.38.0
 */
package org.simplequiz.quizDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Quiz</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.simplequiz.quizDSL.Quiz#getName <em>Name</em>}</li>
 *   <li>{@link org.simplequiz.quizDSL.Quiz#isRandomizeOrder <em>Randomize Order</em>}</li>
 *   <li>{@link org.simplequiz.quizDSL.Quiz#getQuestions <em>Questions</em>}</li>
 * </ul>
 *
 * @see org.simplequiz.quizDSL.QuizDSLPackage#getQuiz()
 * @model
 * @generated
 */
public interface Quiz extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.simplequiz.quizDSL.QuizDSLPackage#getQuiz_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.simplequiz.quizDSL.Quiz#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Randomize Order</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Randomize Order</em>' attribute.
   * @see #setRandomizeOrder(boolean)
   * @see org.simplequiz.quizDSL.QuizDSLPackage#getQuiz_RandomizeOrder()
   * @model
   * @generated
   */
  boolean isRandomizeOrder();

  /**
   * Sets the value of the '{@link org.simplequiz.quizDSL.Quiz#isRandomizeOrder <em>Randomize Order</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Randomize Order</em>' attribute.
   * @see #isRandomizeOrder()
   * @generated
   */
  void setRandomizeOrder(boolean value);

  /**
   * Returns the value of the '<em><b>Questions</b></em>' containment reference list.
   * The list contents are of type {@link org.simplequiz.quizDSL.Question}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Questions</em>' containment reference list.
   * @see org.simplequiz.quizDSL.QuizDSLPackage#getQuiz_Questions()
   * @model containment="true"
   * @generated
   */
  EList<Question> getQuestions();

} // Quiz
