/**
 * generated by Xtext 2.38.0
 */
package org.simplequiz.quizDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.simplequiz.quizDSL.QuizDSLFactory
 * @model kind="package"
 * @generated
 */
public interface QuizDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "quizDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.simplequiz.org/QuizDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "quizDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  QuizDSLPackage eINSTANCE = org.simplequiz.quizDSL.impl.QuizDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.simplequiz.quizDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.simplequiz.quizDSL.impl.ModelImpl
   * @see org.simplequiz.quizDSL.impl.QuizDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Quizzes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__QUIZZES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.simplequiz.quizDSL.impl.QuizImpl <em>Quiz</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.simplequiz.quizDSL.impl.QuizImpl
   * @see org.simplequiz.quizDSL.impl.QuizDSLPackageImpl#getQuiz()
   * @generated
   */
  int QUIZ = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUIZ__NAME = 0;

  /**
   * The feature id for the '<em><b>Randomize Order</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUIZ__RANDOMIZE_ORDER = 1;

  /**
   * The feature id for the '<em><b>Questions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUIZ__QUESTIONS = 2;

  /**
   * The number of structural features of the '<em>Quiz</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUIZ_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.simplequiz.quizDSL.impl.QuestionImpl <em>Question</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.simplequiz.quizDSL.impl.QuestionImpl
   * @see org.simplequiz.quizDSL.impl.QuizDSLPackageImpl#getQuestion()
   * @generated
   */
  int QUESTION = 2;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__TEXT = 0;

  /**
   * The feature id for the '<em><b>Calculated</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__CALCULATED = 1;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__EXPRESSION = 2;

  /**
   * The feature id for the '<em><b>Choices</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__CHOICES = 3;

  /**
   * The number of structural features of the '<em>Question</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.simplequiz.quizDSL.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.simplequiz.quizDSL.impl.ExpressionImpl
   * @see org.simplequiz.quizDSL.impl.QuizDSLPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__VALUE = 0;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.simplequiz.quizDSL.impl.ChoiceImpl <em>Choice</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.simplequiz.quizDSL.impl.ChoiceImpl
   * @see org.simplequiz.quizDSL.impl.QuizDSLPackageImpl#getChoice()
   * @generated
   */
  int CHOICE = 4;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE__TEXT = 0;

  /**
   * The feature id for the '<em><b>Correctness</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE__CORRECTNESS = 1;

  /**
   * The number of structural features of the '<em>Choice</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.simplequiz.quizDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.simplequiz.quizDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.simplequiz.quizDSL.Model#getQuizzes <em>Quizzes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Quizzes</em>'.
   * @see org.simplequiz.quizDSL.Model#getQuizzes()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Quizzes();

  /**
   * Returns the meta object for class '{@link org.simplequiz.quizDSL.Quiz <em>Quiz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Quiz</em>'.
   * @see org.simplequiz.quizDSL.Quiz
   * @generated
   */
  EClass getQuiz();

  /**
   * Returns the meta object for the attribute '{@link org.simplequiz.quizDSL.Quiz#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.simplequiz.quizDSL.Quiz#getName()
   * @see #getQuiz()
   * @generated
   */
  EAttribute getQuiz_Name();

  /**
   * Returns the meta object for the attribute '{@link org.simplequiz.quizDSL.Quiz#isRandomizeOrder <em>Randomize Order</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Randomize Order</em>'.
   * @see org.simplequiz.quizDSL.Quiz#isRandomizeOrder()
   * @see #getQuiz()
   * @generated
   */
  EAttribute getQuiz_RandomizeOrder();

  /**
   * Returns the meta object for the containment reference list '{@link org.simplequiz.quizDSL.Quiz#getQuestions <em>Questions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Questions</em>'.
   * @see org.simplequiz.quizDSL.Quiz#getQuestions()
   * @see #getQuiz()
   * @generated
   */
  EReference getQuiz_Questions();

  /**
   * Returns the meta object for class '{@link org.simplequiz.quizDSL.Question <em>Question</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Question</em>'.
   * @see org.simplequiz.quizDSL.Question
   * @generated
   */
  EClass getQuestion();

  /**
   * Returns the meta object for the attribute '{@link org.simplequiz.quizDSL.Question#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.simplequiz.quizDSL.Question#getText()
   * @see #getQuestion()
   * @generated
   */
  EAttribute getQuestion_Text();

  /**
   * Returns the meta object for the attribute '{@link org.simplequiz.quizDSL.Question#isCalculated <em>Calculated</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Calculated</em>'.
   * @see org.simplequiz.quizDSL.Question#isCalculated()
   * @see #getQuestion()
   * @generated
   */
  EAttribute getQuestion_Calculated();

  /**
   * Returns the meta object for the containment reference '{@link org.simplequiz.quizDSL.Question#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see org.simplequiz.quizDSL.Question#getExpression()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_Expression();

  /**
   * Returns the meta object for the containment reference list '{@link org.simplequiz.quizDSL.Question#getChoices <em>Choices</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Choices</em>'.
   * @see org.simplequiz.quizDSL.Question#getChoices()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_Choices();

  /**
   * Returns the meta object for class '{@link org.simplequiz.quizDSL.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.simplequiz.quizDSL.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the attribute '{@link org.simplequiz.quizDSL.Expression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.simplequiz.quizDSL.Expression#getValue()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Value();

  /**
   * Returns the meta object for class '{@link org.simplequiz.quizDSL.Choice <em>Choice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Choice</em>'.
   * @see org.simplequiz.quizDSL.Choice
   * @generated
   */
  EClass getChoice();

  /**
   * Returns the meta object for the attribute '{@link org.simplequiz.quizDSL.Choice#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.simplequiz.quizDSL.Choice#getText()
   * @see #getChoice()
   * @generated
   */
  EAttribute getChoice_Text();

  /**
   * Returns the meta object for the attribute '{@link org.simplequiz.quizDSL.Choice#getCorrectness <em>Correctness</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Correctness</em>'.
   * @see org.simplequiz.quizDSL.Choice#getCorrectness()
   * @see #getChoice()
   * @generated
   */
  EAttribute getChoice_Correctness();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  QuizDSLFactory getQuizDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.simplequiz.quizDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.simplequiz.quizDSL.impl.ModelImpl
     * @see org.simplequiz.quizDSL.impl.QuizDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Quizzes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__QUIZZES = eINSTANCE.getModel_Quizzes();

    /**
     * The meta object literal for the '{@link org.simplequiz.quizDSL.impl.QuizImpl <em>Quiz</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.simplequiz.quizDSL.impl.QuizImpl
     * @see org.simplequiz.quizDSL.impl.QuizDSLPackageImpl#getQuiz()
     * @generated
     */
    EClass QUIZ = eINSTANCE.getQuiz();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUIZ__NAME = eINSTANCE.getQuiz_Name();

    /**
     * The meta object literal for the '<em><b>Randomize Order</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUIZ__RANDOMIZE_ORDER = eINSTANCE.getQuiz_RandomizeOrder();

    /**
     * The meta object literal for the '<em><b>Questions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUIZ__QUESTIONS = eINSTANCE.getQuiz_Questions();

    /**
     * The meta object literal for the '{@link org.simplequiz.quizDSL.impl.QuestionImpl <em>Question</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.simplequiz.quizDSL.impl.QuestionImpl
     * @see org.simplequiz.quizDSL.impl.QuizDSLPackageImpl#getQuestion()
     * @generated
     */
    EClass QUESTION = eINSTANCE.getQuestion();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUESTION__TEXT = eINSTANCE.getQuestion_Text();

    /**
     * The meta object literal for the '<em><b>Calculated</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUESTION__CALCULATED = eINSTANCE.getQuestion_Calculated();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__EXPRESSION = eINSTANCE.getQuestion_Expression();

    /**
     * The meta object literal for the '<em><b>Choices</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__CHOICES = eINSTANCE.getQuestion_Choices();

    /**
     * The meta object literal for the '{@link org.simplequiz.quizDSL.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.simplequiz.quizDSL.impl.ExpressionImpl
     * @see org.simplequiz.quizDSL.impl.QuizDSLPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__VALUE = eINSTANCE.getExpression_Value();

    /**
     * The meta object literal for the '{@link org.simplequiz.quizDSL.impl.ChoiceImpl <em>Choice</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.simplequiz.quizDSL.impl.ChoiceImpl
     * @see org.simplequiz.quizDSL.impl.QuizDSLPackageImpl#getChoice()
     * @generated
     */
    EClass CHOICE = eINSTANCE.getChoice();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOICE__TEXT = eINSTANCE.getChoice_Text();

    /**
     * The meta object literal for the '<em><b>Correctness</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOICE__CORRECTNESS = eINSTANCE.getChoice_Correctness();

  }

} //QuizDSLPackage
